# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Raffaele Sali personal website
email: raffaele.sali2@unibo.it
description: >- # this means to ignore newlines until "baseurl:"
  Here you can find information and exercises about the courses I'm tutoring and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://raphsa.github.io"
github_username:  raphsa
social_links:
  linkedin: "https://www.linkedin.com/in/raffaelesali"
# Build settings
theme: minima
plugins:
  - jekyll-feed

languages:
  - it
  - en

default_lang: en

navigation:
  it:
    - title: Home
      url: /it/
    - title: Corsi
      url: /it/courses/
    - title: About
      url: /it/about/

  en:
    - title: Home
      url: /en/
    - title: Courses
      url: /en/courses/
    - title: About
      url: /en/about/

exclude:
  - informatica-book
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
